<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<div class="account-login">
	<div class="close-button"></div>
	<div class="page-title">
		<h1><?php echo $this->__('Login') ?></h1>
    </div>
	<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
		<p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
		<ul class="form-list">
			<li>
				<div class="input-box">
					<?php 
						if($this->htmlEscape($this->getUsername())){
							$value = $this->htmlEscape($this->getUsername());
						}else{
							$value = $this->__('Email Address');
						}
					?>
					<input type="text" name="login[username]" value="<?php echo $value; ?>" onblur="if (this.value=='') this.value = '<?php echo $value; ?>'" onfocus="if (this.value=='<?php echo $value; ?>') this.value = ''" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
				</div>
			</li>
			<li>
				<div class="input-box">
					<input type="password" name="login[password]" value="<?php echo $this->__('Password') ?>" onblur="if (this.value=='') this.value = '<?php echo $this->__('Password') ?>'" onfocus="if (this.value=='<?php echo $this->__('Password') ?>') this.value = ''" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
				</div>
			</li>
			<?php echo $this->getChildHtml('form.additional.info'); ?>
		</ul>
		<div class="clear"></div>
		<div class="link-box">or  <a href="#"><?php echo $this->__('Create Account') ?></a></div>
		<div class="actions">
			<button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
		</div>
		<div class="clear"></div>
		<a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
	</form>
    <script type="text/javascript">
		//<![CDATA[
			var dataForm = new VarienForm('login-form', false);
		//]]>
		jQuery('.account-login .link-box a').on('click', function(){
			ajaxLogin("<?php echo $this->getUrl('meigeeactions/register/') ?>", true);
			return false;
		});
    </script>
</div>