<?php
    $_productCollection = $this->getMyCollection();
	$gridMode = $this->sliderGridSelection();
	$visibleProducts = $this->getData('visible_products');
	$productCount = count($_productCollection);
	if (count($_productCollection)) {
	
		$category = $this->catName();
		$_helper = $this->helper('catalog/output');
		$_collectionSize = $this->productsAmount();

		$randId = $this->getWidgetId();
		
		$fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
?>
<?php // Slider ?>
<div class="slider-container widget-container">
<?php if($productCount > $visibleProducts): ?>
    <div class="home-container<?php echo ' '.$gridMode.' alpha omega'; ?>">
		<div class="home-slider-conainer">
			<div class="home-slider es-carousel-wrapper" id="home-slider-<?php echo $randId; ?>">
				<div class="widget-slider">
					<ul class="products-grid carousel-ul">
						<?php $i=0; foreach ($_productCollection as $_product): ?>
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<li class="item">
							<div class="product-img-box">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(400, null); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductLabels($_product); ?><span class="image-box"></span><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 400); ?></a>
							<div class="img-shadow"><div><div></div></div></div>
							<a href="<?php echo $_product->getProductUrl() ?>" class="icon-product-details"></a>
							<?php // Fancybox
							if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
								<a class="fancybox" rel="category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
							<?php endif; // End Fancybox ?>
							<?php if(Mage::getStoreConfig('ajax/general/enabledpro')): ?>
								<button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Quick View') ?></span></span></button>
								<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
							<?php endif; ?>
							</div>
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
							<?php echo $this->getPriceHtml($_product, true) ?>
							<?php if($_product->getRatingSummary()): ?>
							<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							<?php endif; ?>
							<div class="clear"></div>
						</li>
						<?php if (++$i > $_collectionSize-1 ) break; endforeach ?>
					</ul>
				</div>
				<div class = 'next'><em>&nbsp;</em><span>&nbsp;</span></div>
				<div class = 'prev unselectable'><em>&nbsp;</em><span>&nbsp;</span></div>
			</div>
			<div class="clear"></div>
		</div>
    </div>
    <div class="clear"></div>
    <?php else: ?>
		<div class="no-widget"><?php echo $this->__("Warning: Please make sure you have %s+ products to display in the slider, otherwise widget won't be displayed", $visibleProducts+1) ?></div>
	<?php endif; ?>
</div>

<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
<script type="text/javascript">
jQuery(window).load(function(){
    jQuery('#home-slider-<?php echo $randId; ?> .widget-slider').iosSlider({
      responsiveSlideWidth: true,
      snapToChildren: true,
      desktopClickDrag: true,
      infiniteSlider: true
	  <?php echo $this->getSliderOptions(); ?>,
      navNextSelector: '#home-slider-<?php echo $randId; ?> .next',
      navPrevSelector: '#home-slider-<?php echo $randId; ?> .prev'
	  <?php if(isset($sliderConfig ['autoSlide'])): ?>, autoSlide: <?php echo $sliderConfig ['autoSlide']; ?><?php endif; ?>
	  <?php if(isset($sliderConfig ['autoSlideTimer'])): ?>, autoSlideTimer: <?php echo $sliderConfig ['autoSlideTimer']; ?><?php endif; ?>
    });
	
	function widget_slider_height_<?php echo $randId; ?>(){
		var widget_slider_height = 0;
		jQuery('#home-slider-<?php echo $randId; ?> .products-grid li.item').each(function(){
			if(jQuery(this).height() > widget_slider_height){
				widget_slider_height = jQuery(this).height();
			}
		})
		jQuery('#home-slider-<?php echo $randId; ?> .widget-slider').css({
			'min-height': widget_slider_height+15,
			'height': 'auto'
		});
	}
	setTimeout(function(){
		widget_slider_height_<?php echo $randId; ?>();
	}, 500);
	jQuery(window).resize(function(){widget_slider_height_<?php echo $randId; ?>();});
	
	
  });
  
	jQuery(document).ready(function(){
		jQuery('.ajax-fancybox').fancybox(
			{
			   hideOnContentClick : true,
			   width:600,
			   autoDimensions: true,
			   type : 'iframe',
			   showTitle: false,
			   scrolling: 'no',
			   onComplete: function(){
				jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
					jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
					jQuery.fancybox.resize();
				 });

			   }
			}
		);
	});
	function showOptions(id){
		jQuery('#fancybox'+id).trigger('click');
	}
	function setAjaxData(data,iframe){
		if(data.status == 'ERROR'){
			alert(data.message);
		}else{
			if(jQuery('.top-cart')){
				jQuery('.top-cart').replaceWith(data.sidebar);
			}
			/* if(jQuery('.header .links')){
				jQuery('.header .links').replaceWith(data.toplink);
			} */
			jQuery.fancybox.close();
			jQuery('body').append('<div class="add-to-cart-success">' + data.message +' <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><?php echo $this->__('Go to Shopping Cart') ?></span></a><a href="#" class="btn-remove"><i class="icon-remove"></i></a></div>');
				setTimeout(function () {jQuery('.add-to-cart-success').slideUp(500)}, 5000);
				jQuery('.add-to-cart-success a.btn-remove').click(function(){
					jQuery(this).parent().slideUp(500);
					return false;
				});
		}
	}
	function setLocationAjax(url,id){
		url += 'isAjax/1';
		url = url.replace("checkout/cart","ajax/index");
		jQuery('#ajax_loader'+id).show();
		try {
			jQuery.ajax( {
				url : url,
				dataType : 'json',
				success : function(data) {
					jQuery('#ajax_loader'+id).hide();
					setAjaxData(data,false);
				}
			});
		} catch (e) {
		}
	}
</script>
<?php 
	unset ($randId);
}
?>